# Site settings
title: Garrett Woodbridge
description:
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.garrettwoodbridge.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Garrett Woodbridge
user_description: I'm a senior at Oklahoma State University pursuing a Bachelors in Electrical Engineering.
user_title: Electrical Engineer
email: garrett.a.woodbridge@gmail.com
# twitter_username: lorem_ipsum
github_username:  gwoodbridge
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-77262511-5"

exclude: ['package.json', 'src' , 'node_modules']
